version: '{build}'
branches:
  only:
  - master
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
services:
  - mssql2017
build:
  verbosity: detailed
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\src\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: I8MDsKJSklOf0CRkxE+6RSwmkwGjOpiQGmJohTRtbNInFCdFmwTBA73UsRuUmABx
  on:
    appveyor_repo_tag: true