version: '{build}'
branches:
  only:
  - master
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
services:
  - mssql2017
build:
  verbosity: detailed
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\src\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: oy2kyaky4qdbou7qvxrqwfbhne2d5evetnpajlxgnb5d7u
  on:
    appveyor_repo_tag: true
on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot